### ISSUE TITLE
泡芙云好像跑路了，账号被清了

### ISSUE THREAD

**Issue by ZinLiao** [limbopro/paolujichang#4]
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/12324444/221084920-a5146def-8ed8-442d-98ad-da3225c0ad14.png">

还有10个月的费用呢，痛

**Comment by limbopro** [comment]
相当于被恶意清除吗？

**Comment by yanggetit** [comment]
还没啊，你别吓我

**Comment by yanggetit** [comment]
还没有，你别吓我
