### ISSUE TITLE
Pigchaproxy疑似跑路(已确认关闭)

### ISSUE THREAD

**Issue by lkedlkk** [limbopro/paolujichang#47]
机场名称：Pigchaproxy
机场网址：https://pigpigchacha.github.io/officialsite/          有两个分支网站均无法进入
机场状态：跑路预警，暂无法确认
已使用时长：1年
近期续费套餐时长：1年
能否与机场方取的联系：否
不可用情况起止时间：上周开始
1周内的不可用天数：7

老牌机场，加入电报群也有一堆人问，但是管理并未回复，有人放出消息作者疑似被抓，也有另一个消息为软件被攻击，暂时无法确认。

**Comment by lkedlkk** [comment]
刚才去该机场对应的仓库查看了一下，有人说明是作者被开盒索要钱了，并且有图片(图片中写的是在重庆内地)证明所以大概率为真，所以被抓的概率很大，现在为服务器到期未续费导致的无法使用(猜测)

**Comment by lkedlkk** [comment]
今天的最新消息，官方电报群已经转让给快连了，已确认确实跑路(或是被抓)。

**Comment by username-su** [comment]
> 机场名称：Pigchaproxy 机场网址：https://pigpigchacha.github.io/officialsite/ 有两个分支网站均无法进入 机场状态：跑路预警，暂无法确认 已使用时长：1年 近期续费套餐时长：1年 能否与机场方取的联系：否 不可用情况起止时间：上周开始 1周内的不可用天数：7
> 
> 老牌机场，加入电报群也有一堆人问，但是管理并未回复，有人放出消息作者疑似被抓，也有另一个消息为软件被攻击，暂时无法确认。
在https://www.pigcha.com.hk/，pigcha的香港网站上只剩下了：
{
    "code": 0,
    "data": {},
    "msg": "Love is around"
}
不知道什么意思🤔

**Comment by username-su** [comment]
!!!!他以一种莫名其妙的方式复活了，但是不是完全复活。官网已经没法用，但在github的官网https://pigpigchacha.github.io/officialsite/;;会跳转到一个很新的机场viewturbo（https://web.vtfly.com/）

**Comment by xiaoguaia** [comment]
现在他的项目库里所有的地址都在指向一个新的机场viewturbo，里面的价格和Pigchaproxy 一模一样，手机端打开之前的Pigchaproxy 软件就回提示新的机场的地址

**Comment by xiaoguaia** [comment]
> ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补

客服?没有找到客服的啊。

**Comment by 666nbplus** [comment]
> > ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补
> 
> 客服？没找到客服的啊。

我是可以直接登录原来的账号的，登录之后显示已经陪伴我1054天[笑哭]，客服只有邮件，在网站找到联系，找到亚洲客服邮件就行，我发完大概20个小时才回复我

**Comment by 666nbplus** [comment]
> > ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补
> 
> 客服？没找到客服的啊。

https://web.vtfly.com/zh/about#Contact

**Comment by xiaoguaia** [comment]
> > > ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补
> > 
> > 
> > 客服？没找到客服的啊。
> 
> https://web.vtfly.com/zh/about#Contact

我用之前账号登录是没有了的，又重新注册了，ok看到了邮箱

**Comment by 666nbplus** [comment]
> > > > ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补
> > > 
> > > 
> > > 客服？没找到客服的啊。
> > 
> > 
> > https://web.vtfly.com/zh/about#Contact
> 
> 我用之前账号登录是没有了的，又重新注册了，ok看到了邮箱

我问了客服，pigcha的老板确实被抓了

**Comment by 666nbplus** [comment]
> > > > ​复活了，进原来的官网会自动跳转到新的网址，能直接登录原来的账号，流量和套餐都还在，如果没有给客服发邮件会补
> > > 
> > > 
> > > 客服？没找到客服的啊。
> > 
> > 
> > https://web.vtfly.com/zh/about#Contact
> 
> 我之前用账号登录是没有看到的，又重新注册了，ok了邮箱

我问了客服，客服说pigcha的老板确实被抓了

**Comment by mankuok829** [comment]
10.29 Email: 

亲爱的 Pigcha 用户，您好：

我们想向您表达最真诚的歉意。
由于技术原因，Pigcha 的服务曾中断近一年，这期间给您带来的不便，我们深感抱歉。
感谢您在这段时间的理解与等待，您的信任让我们重新出发。

新官网链接：https://web.sportsphp.com/
官方邮箱：support@marslinkvpn.com

**Comment by DirtyBoy-53** [comment]
但是，这个新链接的价格比起以前更是贵了不少啊，道友们有别的平民推荐吗
