### ISSUE TITLE
[机场跑路/预警]FSCloud疑似跑路

### ISSUE THREAD

**Issue by hc-advokate** [limbopro/Paolujichang#57]
## 详情说明

机场名称：FSCloud
机场网址：fscloud.vip https://web.fscloud.cc/
机场状态：跑路预警
已使用时长：半年
近期续费套餐时长：年
能否与机场方取的联系：否
不可用情况起止时间：11.05-今.2024
1周内的不可用天数：2

其他补充：
![20241107-095510](https://github.com/user-attachments/assets/ba82f853-fbc0-49a4-aac1-95fe7caeab9c)

---

以下信息请在提交issue时完整保留。

## 提交issues 及回复须知

✅ **如实表述，不捏造是非**；在提交 issue 前请确保已尝试与官方沟通但未得到解决的，各方面均已表明该机场已跑路或有跑路倾向的；

🔔 如有可能，请提供节点不可用**截图等其他方面的佐证**（群聊禁言/群聊被清空/工单不回复/官方公告/...），截图中可能**涉及隐私的部分**请进行部分或完全**模糊/马赛克处理**（如邮箱/完整订单号/完整时间戳等...）；

⚠️ 对于 issues 中存在的**推广/投机**行为，等与本计划（跑路机场合集）主题**非相关话题**，请注意鉴别，一经发现，视情节或被**隐藏/删除**处理，由此可能给某些用户带来的“不便”，敬请谅解；

## 细节补充

♻️ 因为机场各个用户遇到或了解到的信息可能存在差异，**如果看到该issue的你也是该机场用户/或官方人员**，欢迎**回复以完善与该主题相关的细节**以便大家能更全面的了解；

**Comment by LeHungryBoi** [comment]
有一个叫一分机场.com的好像跟FSCloud是同一个人做的，网页长的一样，价格翻倍。
我在FSCloud4的tg群里发了个🤡，然后加了一分机场的tg群，被管理员秒封。

**Comment by hc-advokate** [comment]
> 有一个叫一分机场.com的好像跟FSCloud是同一个人做的，网页长的一样，价格翻倍。 我在FSCloud4的tg群里发了个🤡，然后加了一分机场的tg群，被管理员秒封。

哈，好像又恢复了，其实机场主没有很多，就那么几个，这个玩意轻度用户用或者备用我感觉还行。不加他们的 tg 没啥用，跑路的时候啥都找不到。😄

**Comment by prepare007** [comment]
感觉已经跑路了，用了一年，本来想续订，下客户端下不了最新的，新注册的也试用不了

**Comment by hui-cat** [comment]
有没有最新的网址，现在fscloud.vip 和 fscloud.cc都挂了

**Comment by symmetricislzl** [comment]
> 有没有最新的网址，现在fscloud.vip 和 fscloud.cc都挂了

后者可以用啊？

**Comment by bingwei** [comment]
还活着。但网络质量不稳定
https://dash3.fscloud.homes/#/

**Comment by symmetricislzl** [comment]
咦，为啥会把这个邮件发给我，这是fscloud官方发的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月27日(周五) 下午2:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [limbopro/Paolujichang] [机场跑路/预警]FSCloud疑似跑路 (Issue #57)


bingwei left a comment (limbopro/Paolujichang#57)
 
还活着。但网络质量不稳定
 https://dash3.fscloud.homes/#/

**Comment by jxxxus** [comment]
忘记密码都改不了，主页就有登录界面，客服都找不到

**Comment by symmetricislzl** [comment]
才充了钱。。伤感



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年7月21日(周一) 晚上11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [limbopro/Paolujichang] [机场跑路/预警]FSCloud疑似跑路 (Issue #57)


jxxxus left a comment (limbopro/Paolujichang#57)
 
忘记密码都改不了，主页就有登录界面，客服都找不到

**Comment by Kikibuby** [comment]
爆崩溃，三天了所有节点都用不了，telegram也登不上，工单发了也没回信
