### ISSUE TITLE
投稿银河录像局

### ISSUE THREAD

**Issue by fipsm** [limbopro/Paolujichang#58]
![Screenshot_2024-11-13-19-58-32-643_com.android.chrome.jpg](https://github.com/user-attachments/assets/9be97e95-c4dd-4d1e-afd3-e02996d1780b)

![Screenshot_2024-11-10-18-31-13-387_com.android.chrome.jpg](https://github.com/user-attachments/assets/0325a2a4-a684-45d1-bd6e-a156e4d09e75)

![Screenshot_2024-11-10-18-31-25-275_com.netflix.mediaclient.jpg](https://github.com/user-attachments/assets/85320ef3-29fa-4a70-996e-33daa0a89bfd)

现在帐号已经被奈飞给停用了，客服不处理

**Comment by limbopro** [comment]
是否有联系客服反应相关情况？联系客服后过去了多少时间？

**Comment by fipsm** [comment]
> 是否有联系客服反应相关情况？联系客服后过去了多少时间？

![Screenshot_2024-11-14-10-27-59-036_com.tencent.mm.jpg](https://github.com/user-attachments/assets/38d76305-3977-4f6b-936e-716b28f10df1)

没有结果，帐号用不好了

**Comment by limbopro** [comment]
因为博主这边收到的反馈很少，目前包括你这一次，一共有2次反馈。前一次已经解决。你可以再尝试联系反馈一下，了解Netflix炸号缘由，让客服跟进一下解决。

跟你所说的一样，如果有问题不处理不解决，频繁的发生，这边也会下架对它的推荐。
