### ISSUE TITLE
fastlink可能要跑路了

### ISSUE THREAD

**Issue by Bruce-1988** [limbopro/Paolujichang#8]
机场名称：Fastlink
官网：https://v2.fastlink-aff02.com/

最近几天开始不稳定，客服也没人回复了，且偷跑流量问题严重 不排除最后圈一波

**Comment by limbopro** [comment]
已更新

**Comment by limbopro** [comment]
<img width="483" alt="截屏2024-01-24 20 50 58" src="https://github.com/limbopro/paolujichang/assets/53378607/b3223339-c9f2-4d64-a3c1-e8bc9fb8b988">

预警撤回。

**Comment by m1sak1** [comment]
没跑路是换网址了吗，好久之前就登不上了，今天又试了试还是不行

**Comment by zjttfs** [comment]
关闭群后,就越来越不稳定了..

**Comment by Saintlord77** [comment]
好几周没连上了

**Comment by AlvinChen12** [comment]
今天发现官网上不去了，订阅也无法更新，才买了不久的一年套餐

**Comment by mrchenmo** [comment]
> 今天发现官网上不去了，订阅也无法更新，才买了不久的一年套餐

我刚试了官网能登上，也能更新节点，就是节点全部超时，要跑路了吗

**Comment by I0me0I** [comment]
域名换了，原来的被墙了
新官网：web03.fastlink.cc

**Comment by HankoZhou** [comment]
支付界面和支付宝一模一样，仔细看域名并不是支付宝官方的域名，不知道有没有风险！

**Comment by kuu-an** [comment]
现在又开始了，全部节点崩掉，想去TG问结果官方群还搞禁言

**Comment by HelloSkyHigh** [comment]
Fastlink已經連不上了 客服沒人理

**Comment by limbopro** [comment]
机场相关方反馈部分地区污染，问题已解决，更新订阅即可。如有问题请第一时间联系客服，工单或官网右下角客服。参阅 https://t.me/airportbbq/24504

**Comment by doream** [comment]
总是流量偷跑，一整天不上网，晚上打开一看今天跑了30G

**Comment by JerryZhongJ** [comment]
连不上了，是不是跑路了？

**Comment by John-Simth** [comment]
> 连不上了，是不是跑路了？

我也连不上，上官网看了下，发现网站在维护

**Comment by joann0309** [comment]
2025.7.16: 4月底购买了半年每月200G套餐，7月的流量直接没有到账。靠流量包续命。与客服纠缠了20天，每天催，每天告诉我流量已到账（并没有）。客服不具备最基本的沟通能力，更不会即时响应。要求退款未果。

**Comment by stylof** [comment]
2025下半年从8月开始吧。 一直不稳定  掉线。   基本上频繁掉线5到10分钟，刚才更离谱 一直掉，客服也不回复消息/或者无效沟通。  我买了一年 还有200多天（大家小心跑路）。 
客服让我更新节点，换软件。没任何作用。

**Comment by xinxuan1587** [comment]
频繁掉线，夜间速度非常慢

**Comment by qinghsi688** [comment]
2006年3月，新加坡和日本的节点挂了，和客服沟通后，新加坡的一直没有修复（已经快1个月了），日本的修复了之后延迟也在300多。跑路概率大大增加，各位小心了。

<img width="362" height="593" alt="Image" src="https://github.com/user-attachments/assets/c347179c-dedc-49bf-a9fd-3b099f5bdfc1" />

**Comment by bankroz** [comment]
最近跑路趋势更加明显，先是速度极慢，然后前几天突然订阅失效，问客服说必须使用他们的软件。因为我刚续费一年，而且电脑禁止安装新软件，找他退款，回复是退款是不可能的，再问啥就都没回复了。

希望对刷到这个帖子的人有帮助，避雷这家吧。

<img width="413" height="366" alt="Image" src="https://github.com/user-attachments/assets/b59c7156-b0f6-4627-af8a-b0b86514787c" />

**Comment by AlvinChen12** [comment]
他们现在一定要安装软件才能用，然后我下载了他们MacBook的软件安装，根本登录不上去，每次登录就是什么服务器错误啥的，已经换了别家VPN了

**Comment by AlvinChen12** [comment]
> 他们现在一定要安装软件才能用，然后我下载了他们MacBook的软件安装，根本登录不上去，每次登录就是什么服务器错误啥的，已经换了别家VPN了

另外联系客服也没人回复

**Comment by steven-zhang-1024** [comment]
為什麼不能提供訂閱連結
